const brands = {
  Nestle: [
    "Nestle",
    "Nestlé",
    "Cerelac",
    "Gerber",
    "NaturNes",
    "Pure Life",
    "Perrier",
    "Pellegrino",
    "Nestle Lion",
    "Nestlé Lion",
    "Lion bar",
    "Nesquik",
    "Aero",
    "Cailler",
    "KitKat",
    "Milkybar",
    "Les Recettes de l'Atelier",
    "Orion",
    "Quality Street",
    "Smarties",
    "Toll House",
    "Blue Bottle Coffee",
    "Nescafé Dolce Gusto",
    "Nescafe Dolce Gusto",
    "Nespresso",
    "Buitoni",
    "Herta",
    "Hot Pockets",
    "Lean Cuisine",
    "Maggi",
    "Stouffer",
    "Thomy",
    "Carnation",
    "Coffee-Mate",
    "La Laitière",
    "La Laitiere",
    "Nido",
    "Milo",
    "Nestea",
    "Chef-Mate",
    "Chef Mate",
    "Minor's",
    "Nescafé",
    "Nescafe",
    "Sjora",
    "Stouffer's",
    "Nutren Junior",
    "Peptamen",
    "Resource",
    "Dreyer's",
    "Dreyer",
    "Extrême",
    "Mövenpick",
    "Movenpick",
    "Nestlé Ice Cream",
    "Nestle Ice Cream",
    "Alpo",
    "Bakers Complete",
    "Beneful",
    "Cat Chow",
    "Dog Chow",
    "Fancy Feast",
    "Felix",
    "Friskies",
    "Gourmet",
    "Purina",
    "Purina ONE",
    "Pro Plan",
  ],
  "General Mills": [
    "Cheerios",
    "Häagen-Dazs",
    "Haagen-Dazs",
    "Haagen Dazs",
    "Annie's",
    "Autumn's Gold",
    "Betty Crocker",
    "Bisquick",
    "Blue Buffalo",
    "Boldcultr",
    "Bugles",
    "Cascadian Farm",
    "Chex Cereal",
    "Chex Mix",
    "Cinnamon Toast Crucnh",
    "Cocoa Puffs",
    "cookie Crisp",
    "Doolies",
    "Dunkaroos",
    "Fiber one",
    "food should taste good",
    "Gardetto's",
    "Golden grahams",
    "Green Giant",
    "Häagen Dazs",
    "Jus-rol",
    "larabar",
    "Latina fresh",
    "Lucky charms",
    "Monster cereal",
    "Muir glen",
    "Nature Valley",
    "Old El Paso",
    "Pillsbury",
    "Pillsbury Atta",
    "Progresso",
    "Raisin Nut Bran",
    "Ratio Food",
    "Reese-s Puffs",
    "Totino's",
    "Trix",
    "Wanchai Ferry",
    "Wheaties",
    "Yoki",
    "Yoplait",
  ],
  Bacardí: ["Bacardi", "Bacardí"],
  Pepsico: [
    "Pepsi",
    "Lays ",
    "Lay's",
    "Mtn Dew",
    "Mountain Dew",
    "Doritos",
    "Gatorade",
    "Tropicana",
    "Quaker Oats",
    "Lipton",
    "Frapuccino",
    "Aquafina",
    " Ruffles",
    "Cheetos",
    "Brisk",
    "Tostitos",
    "Fritos",
    "Sierra Mist",
    "7up",
    "Seven Up",
    "Sevenup",
    "Mirinda",
    "Walkers",
  ],
  Bayer: ["Bayer"],
  "Colgate-Palmolive": [
    "Colgate",
    "Palmolive",
    "Protex",
    "Sanex",
    "Softsoap",
    "Hills",
    "Hill's",
    "Sorriso",
    "Speed Stick",
    "Suavitel",
    "Murphy Oil Soap",
    "Meridol",
    "Irish Spring",
    "Tom's of Maine",
    "Toms of Maine",
    "Tahiti",
    "Softlan",
    "Ajax",
    "Fleecy",
    "Pinho Sol",
    "Axion",
    "Cuddly",
    "Sta-Soft",
    "Sta Soft",
    "Elmex",
    "Fabuloso",
    "Soupline",
    "Pca skin",
    "Filorga",
    "Eltamd",
    "Danklorix",
  ],
  "Kellogg's": [
    "Pringles",
    "Coco Pops",
    "Cocopops",
    "Crunchy Nut",
    "Crunchynut",
    "Frosties",
    "Kellogg",
    "Corn Flakes",
    "Krave",
    "Nutri-Grain",
    "NutriGrain",
    "Pop Tarts",
    "Poptarts",
    "Rice Krispies",
    "Special K",
    "SpecialK",
  ],
  "Kraft Heinz": [
    "Heinz",
    "Kraft",
    "Oscar Mayer",
    "Ore-lda",
    "Velveeta",
    "Smart Ones",
    "Caprisun",
    "Wattie's",
    "Kool-Aid",
    "Kool Aid",
    "Jell-o",
    "Philadelphia",
    "Golden Circle",
    "Lunchables",
    "Pudliszki",
    "Maxwell House",
    "Grey Poupon",
    "Honig",
    "Plasmon",
    "Quero",
  ],
  Mars: [
    "Api fish",
    "Aquarian",
    "Buckeye",
    "Cesar",
    "Dreamis",
    "Eukanuba",
    "Greenies",
    "Iams",
    "Nutro",
    "Pedigree",
    "Royal Canin",
    "Sheba",
    "Spillers",
    "Temptations",
    "Winergy",
    "Whiskas",
    "Musketeers",
    "Altoids",
    "American Heritage",
    "Amicelli",
    "Balisto",
    "Big Red",
    "Bigred",
    "Bounty",
    "Celebrations",
    "Combos",
    "Doublemint",
    "Eclipse",
    "Galaxy caramel",
    "Galaxy milk",
    "Galaxy ripple",
    "Galaxy cookie",
    "Galaxy cookieі",
    "Galaxy minstrels",
    "Galaxy counters",
    "Galaxy honeycomb",
    "Galaxy crispy",
    "Galaxy salted",
    "Galaxy chunks",
    "Galaxy fusions",
    "Galaxy truffles",
    "Goodness Knows",
    "Hubba Bubba",
    "Juicy fruit",
    "Life savers",
    "m&m",
    "maltesers",
    "mars ",
    "milky way",
    "Orbit",
    "Skittles",
    "Starburst",
    "Twix",
    "Winterfresh",
    "Winter Fresh",
    "Wrigleys Extra",
    "Extra Peppermint Gum",
    "Extra White Gum Bottle",
    "Extra Cool Breeze Gum",
    "Extra Ice Peppermint",
    "Extra White Peppermint",
    "Airwaves",
    "Spearmint",
    "Ben's",
    "Dolmio",
    "Ebly",
    "Kantong",
    "Masterfoods",
    "Master foods",
    "Miracoli",
    "Pamesello",
    "Raris",
    "Ráris",
    "Royco",
    "Seeds of Change",
    "Suzi wan",
    "Suziwan",
    "tasty bite",
    "tastybite",
    "Revels",
  ],
  Unilever: [
    "Dove",
    "Ben & Jerry",
    "Comfort fabric",
    "Comfort pure",
    "Comfort dermatologically",
    "Comfort ultra",
    "Comfort ulmte",
    "Comfort blue",
    "Comfort creations",
    "Domestos",
    "Hellmann",
    "Knorr",
    "Lifebuoy",
    "Magnum",
    "Omo laundry",
    "Omo sensitive",
    "Omo active",
    "Omo touch",
    "Rexona",
    "Seventh Generation",
    "Sunsilk",
    "Wall's",
    "Bango",
    "Lynx",
    "Axe desodorante",
    "Axe deodorant",
    "desodorante Axe",
    "deodorant Axe",
    "dark temptation",
    "black rock axe",
    "black gel",
    "cookies axe",
    "cedro axe",
    "spray axe",
    "axe spray",
    "chill axe",
    "black axe",
    "Cif",
    "The Vegetarian Butcher",
    "Equilibra",
    "Olly",
    "Liquid I.V.",
    "Smartypants",
    "Onnit",
    "Vaseline",
  ],
  "Mondelēz International": [
    "Cadbury",
    "Alpen Gold",
    "Barni",
    "Belvita",
    "Bournvita",
    "Chips Ahoy",
    "Clorets",
    "Club Social",
    "Cote d'or",
    "Côte d'or",
    "Dairylea",
    "Daim",
    "Enjoy life",
    "Freia",
    "Halls",
    "Honey maid",
    "Kinh Do",
    "Lacta ",
    "Marabou",
    "Maynards",
    "Milka",
    "Oreo",
    "Perfect Snacks",
    "Ritz",
    "Royal Baking Powder",
    "Sour Patch Kids",
    "Stride",
    "Tang ",
    "Tate's Bake Shop",
    "Tiger",
    "Toblerone",
    "Trident",
    "Triscuit",
    "Tuc",
    "Wheat Thins",
  ],
  "Philip Morris": ["Marlboro", "Iqos"],
  "Procter & Gamble": [
    "Aussie",
    "Head & Shoulders",
    "Herbal Essence",
    "Olay",
    "SK-II",
    "Pantene",
    "Pampers",
    "Always",
    "Tampax",
    "Ariel",
    "Bold 2in1",
    "Bold 2 in 1",
    "Daz",
    "Fairy MaxPower",
    "Fairy Clean",
    "Fairy Antibacterial",
    "Fairy original",
    "Fairy washing",
    "Fairy platinum",
    "Fairy pure",
    "Fairy all",
    "Fairy rinse",
    "Fairy non",
    "Fairy fabric",
    "Fairy snuggly",
    "Lenor",
    "Ambi Pur",
    "Febreze",
    "Viakal",
    "Clearblue",
    "Fixodent",
    "Old Spice",
    "Oral-B",
    "Oral B",
    "Seven Seas",
    "Vicks",
    "Braun",
    "Gillette",
    "Ausonia",
    "Evax",
    "Dodot",
    "H&S",
    "Don Limpio",
    "Swiffer",
    "La Recette Essentielle",
    "Bear Fruits",
    "Mr Propre",
    "Mastro Lindo",
    "Kukident",
    "ZzzQUIL",
    "Bion3",
  ],
  Barilla: [
    "Barilla",
    "Voiello",
    "Filiz",
    "Misko",
    "Yemina Vesta",
    "Catelli",
    "Lancia",
    "Pasta evangelis",
    "Tolerant organic",
    "Mulino Bianco",
    "Gan cereale",
    "Pan di stelle",
    "Pavesi",
    "Harrys",
    "Wasa",
  ],
  "SC Johnson": [
    "Glade",
    "Oust ",
    "Bayclin",
    "Bonami",
    "Ceramicol",
    "Duck",
    "Canard",
    "Pato",
    "WC-Ente",
    "WC Ente",
    "Drano",
    "Fantastik",
    "Freedom carpet foam",
    "Klaro",
    "Lysoform",
    "Mr muscle",
    "Mr.muscle",
    "Mr musculo",
    "Mr.musculo",
    "Pledge",
    "Blem",
    "Bravo",
    "Pliz",
    "Pronto",
    "Roma coco",
    "Scrubbing bubbles",
    "Windex",
    "null null",
    "Eend action",
    "Eend nr",
    "Eend extra",
    "Eend vloeibaar",
    "Eend stortbak",
    "Eend active",
    "Eend aqua",
    "Eend fresh",
    "Eend wc",
    "wc Eend",
    "Autan",
    "Off!",
    "Baygon",
    "Chemotox",
    "Fuyi",
    "Pyrel",
    "Raid",
    "Polil",
    "Ziploc",
    "Saran",
    "Salamander",
    "Woly",
    "Grand Prix",
    "Carnu",
    "Babyganics",
    "Caldrea",
    "Ecover",
    "Method kitchen",
    "Method bathroom",
    "Method wood",
    "Method glass",
    "Method spray",
    "Method multisurface",
    "Method dish",
    "Method men",
    "Mrs meyer",
  ],
  "Kimberly-Clark": [
    "Andrex",
    "Huggies",
    "Goodnites",
    "Drynites",
    "Little Swimmers",
    "KleenBebe",
    "Kleen Bebe",
    "Green Finger",
    "GreenFinger",
    "Kleenex",
    "Hakle",
    "Cottonelle",
    "Scottex",
    "Petalo",
    "Wondersoft",
    "Scott ",
    "Viva",
    "U by Kotex",
    "Kotex",
    "Intimus",
    "Camelia",
    "WypAll",
    "Kimtech",
    "Kleenguard",
    "Depend",
    "Poise",
    "Plenitud",
  ],
  Bonduelle: ["Bonduelle"],
  Philips: ["Philips"],
  Chipita: ["7 days", "7days", "Fineti", "Chipicao"],
  "De Cecco": ["Dececco", "De cecco"],
  Borges: [
    "Borges",
    "Capricho Andaluz",
    "Caramia",
    "ITLV",
    "Ortalli",
    "H&GSO",
    "Healthy & Green Solid",
    "Agreena",
    "Pacific Choice",
    "Tramier",
    "Eco Natura",
  ],
  "Grupo Fuertes": [
    "Agrifusa",
    "Cefusa",
    "Procavi",
    "El Pozo",
    "Elpozo",
    "Fripozo",
    "Sediasa",
    "Palancares",
    "Luzon bodegas",
    "Luzon",
    "Aqua Deus",
    "Aquadeus",
  ],
  "JDE Peet's": [
    "Douwe Egberts",
    "Kenco",
    "Peet's",
    "Stumptown",
    "Tassimo",
    "Gevalia",
    "Pickwick",
    "Pilao",
    "Old Town",
    "Oldtown",
    "Jacobs",
    "Moccona",
    "Mighty Leaf",
    "Tiora",
  ],
  Lactalis: [
    "Président",
    "President",
    "Galbani",
    "Lactel",
    "Bridel",
    "Ambassador",
    "Santal",
    "Societé",
    "Societe",
    "Seriously",
    "Pauls",
    "Laicran",
    "QBB",
    "Valbreso",
    "Smeds",
    "Parmalat",
    "Puleva",
    "Picot",
    "Milumel",
    "Celia",
    "Bridelight",
    "Chaussee Moines",
    "Chaussée Moines",
    "Istara",
    "Lanquetot",
    "Roitelet",
    "Lou Perac",
    "Lou Pérac",
    "Rondele",
    "Rondelé",
    "Rouy",
    "Salakis",
    "Siggit",
    "Babybel",
    "Boursin",
    "Kiri",
    "Vache qui rit",
    "Leerdammer",
  ],
  Storck: [
    "Toffifee",
    "Merci",
    "Nimm2",
    "Nimm 2",
    "Riesen",
    "Knoppers",
    "Werther's original",
    "Mamba",
    "Bendicks",
    "Bunte Welt",
  ],
  Zwack: ["Zwack"],
  Anecoop: [
    "Bouquet",
    "Naturane",
    "Bouquet Bio",
    "Bouquet Naturane Zero",
    "Black Cat",
    "Nadal Anecoop",
    "Amatista Moscato",
    "Icono Merlot",
    "Icono Cabernet Sauvignon",
    "Icono Chardonnay",
    "Icono seleccion",
    "Icono selección",
    "Icono Syrah",
    "Juan de juanes",
    "lvec blue",
    "lvec green",
    "lvec orange",
    "Reymos",
    "Venta del Puerto",
    "Vida moscato",
  ],
  Campari: ["Campari"],
  Carmim: [
    "Carmim",
    "Reguengos",
    "Olaria",
    "Monsaraz",
    "Pátria",
    "Terras d'el Rei",
    "Real Grei",
    "Regia Colheita",
    "Régia Colheita",
    "Bom juiz",
  ],
  Delonghi: ["Delonghi"],
  Ehrmann: ["ehrmann"],
  Gruma: ["Maseca", "Mission tortilla", "Lacima", "La cima", "Delicados"],
  Hochland: [
    "Hochland",
    "Almette",
    "Grunlander",
    "Grünländer",
    "Cathedral city",
    "SimplyV",
    "Simply V",
    "Patros",
    "Valbrie",
    "Gervais",
    "Valbon",
    "Fetaxa",
  ],
  "Japan Tobacco": [
    "Winston",
    "Mevius",
    "Camel",
    "Benson & Hedges",
    "Natural American Spirit",
    "Sobraine",
    "Silk cut",
    "Ploom",
    "Logic vaping",
  ],
  "Johnson & Johnson": [
    "Tylenol",
    "Motrin",
    "Zyrtec",
    "Benadryl",
    "Zarbee",
    "Nicorette",
    "Calpol",
    "Codral",
    "Doktor mom",
    "Dolormin",
    "Frenadol",
    "Imodium",
    "ORSL",
    "Pepcid",
    "Sudafed",
    "Visine",
    "Neutrogena",
    "Aveeno",
    "Dr.Ci:Labo",
    "Neostrata",
    "Dabao",
    "OGX",
    "Le petit marsellais",
    "Bebe young care",
    "Clean & Clear",
    "Exuviance",
    "Labo labo",
    "Lubriderm",
    "Piz buin",
    "Regaine",
    "Rogaine",
    "Sundown",
    "Listerine",
    "Band-Aid",
    "Johnson's",
    "Aveeno baby",
    "Carefree",
    "Desitin",
    "Neosporin",
    "O.B.",
    "Penaten",
    "Polysporin",
    "Stayfree",
  ],
  "Red Bull": ["Red Bull", "RedBull"],
  "Ritter Sport": ["Ritter Sport"],
  Beiersdorf: [
    "Nivea",
    "Eucerin",
    "La prairie",
    "Coppertone",
    "Labello",
    "Hansaplast",
    "8x4",
    "Floren",
    "Hidrofugal",
    "Gammon",
    "Skin stories",
    "Florena",
    "Stop the water while using me",
    "Chaul",
    "o.w.n",
    "Chantecaille",
  ],
  Ferrero: [
    "Ferrero",
    "Nutella",
    "Kinder",
    "TicTac",
    "Tic Tac",
    "Raffaello",
    "Golden Gallery",
  ],
  Herbalife: ["Herbalife"],
  Kotanyi: ["Kotanyi"],
  Whirlpool: ["Whirlpool"],
  "Groupe Savencia": [
    "Caprice des dieux",
    "Saint Agur",
    "St Moret",
    "Fromage tartare",
    "Saint Albray",
    "Fol Epi",
    "Elle & Vire",
    " balade ",
    "Geramont",
    " Bresso ",
    "Richesmont",
    "Chavroux",
    "Burgo de Arias",
    "Lucina",
    "Le rustique",
    " Ile de France ",
    "Alouette",
    "Polenghi",
    "Santa Rosa",
    "Milkana",
    "Epoisses Berthaut",
    "Roquefort Papillon",
    "Fauquet",
    "Etorki",
    "Holland Master",
    "Bresse Bleu",
    "Esquirrou",
    "Au bouchon",
    "Rogue Creamery",
    "Dorothy's",
  ],
  "Coca-Cola": [
    "Coca-Cola",
    "Coca Cola",
    "Cocacola",
    "Coke",
    "Adés",
    "Aha Sparkling",
    "Appletiser",
    "Aquarius",
    "Barq's",
    "Bodyarmor",
    "Costa coffee",
    "Dasani",
    "Diet coke",
    "Dogadan ",
    "Fanta",
    "Fuzetea",
    "Gold Peak Tea",
    "Honest Tea",
    "Innocent ",
    "Minute Maid",
    "Peace Tea",
    "Powerade",
    "Schweppes",
    "Sprite",
    "Topo Chico",
    "Glaceau",
  ],
};
